"""
LLM-generated interest theme recommender.

This strategy uses LLM to generate interest themes from the user's recently
marked papers, then recommends papers matching those themes.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timedelta
from typing import TYPE_CHECKING, List

from daily_paper.config import Config
from daily_paper.embeddings.client import EmbeddingClient
from daily_paper.embeddings.utils import cosine_similarity
from daily_paper.recommenders.base import BaseRecommender, RecommendationContext, RecommendationResult
from daily_paper.summarizers.llm_client import LLMClient

if TYPE_CHECKING:
    from daily_paper.database.models import Paper

logger = logging.getLogger(__name__)


class LLMThemeRecommender(BaseRecommender):
    """
    Recommend papers based on LLM-generated interest themes.

    This strategy:
    1. Generates themes from the user's recently interested papers (real-time, no database storage)
    2. Recommends papers semantically similar to those themes

    Themes are generated by analyzing the user's recently interested papers
    and extracting key research areas/topics.

    Typical usage:
        >>> recommender = LLMThemeRecommender(embedding_client, config, llm_client)
        >>> context = RecommendationContext(candidate_papers=papers, interested_paper_ids={...})
        >>> results = recommender.recommend(context, top_k=10)

    Attributes:
        config: Application configuration.
        embedding_client: Embedding service client.
        llm_client: LLM service client for theme generation.
    """

    def __init__(
        self,
        embedding_client: EmbeddingClient,
        config: Config = None,
        llm_client: LLMClient = None,
    ):
        """
        Initialize the LLM theme recommender.

        Args:
            embedding_client: Embedding service client.
            config: Application configuration.
            llm_client: LLM service client.
        """
        super().__init__(embedding_client, config)
        self.config = config or Config.from_env()
        self.llm_client = llm_client or LLMClient(self.config.llm)

    @property
    def strategy_name(self) -> str:
        """Return strategy identifier."""
        return "llm_themes"

    def recommend(
        self,
        context: RecommendationContext,
        top_k: int = 10,
    ) -> List[RecommendationResult]:
        """
        Generate recommendations based on LLM-generated interest themes.

        Args:
            context: RecommendationContext containing candidate papers and interested paper IDs.
            top_k: Maximum number of recommendations to return.

        Returns:
            List of RecommendationResult sorted by theme similarity descending.

        Implementation details:
            - Generates themes from interested papers in context (real-time)
            - Calculates semantic similarity between papers and themes
            - Returns top-K papers most similar to themes
        """
        # Get configuration
        min_similarity = self.config.recommendation.min_similarity

        # Get interested papers from context
        interested_papers = context.get_interested_papers()

        if not interested_papers:
            logger.warning("No interested papers in context for theme generation")
            return []

        logger.info(f"LLM themes: Found {len(interested_papers)} interested papers")

        # Generate themes from interested papers
        themes = self._generate_themes_from_papers(interested_papers)

        if not themes:
            logger.warning("Failed to generate themes from interested papers")
            return []

        logger.info(f"LLM themes: Generated {len(themes)} themes")

        # Filter out read papers
        papers = self._filter_read_papers(context)
        if not papers:
            logger.warning("No papers after filtering read papers")
            return []

        # Validation: Filter papers with summaries or sufficient abstracts
        valid_papers = []
        for paper in papers:
            # Check if paper has summaries
            if paper.summaries:
                valid_papers.append(paper)
                continue

            # No summary: check abstract length
            if paper.abstract and len(paper.abstract.strip()) >= 100:
                valid_papers.append(paper)
            else:
                logger.debug(
                    f"Paper {paper.id} skipped: no summary and short abstract"
                )

        if not valid_papers:
            logger.warning(
                "LLM themes: No valid papers with summaries or sufficient abstracts"
            )
            return []

        papers = valid_papers
        logger.info(f"LLM themes: {len(papers)} valid papers after validation")

        # Generate embeddings for themes
        try:
            theme_embeddings = self.embedding_client.get_embeddings(themes)

            # Generate embeddings for candidate papers
            paper_texts = []
            for paper in papers:
                text_parts = []
                if paper.title:
                    text_parts.append(paper.title)
                if paper.abstract:
                    text_parts.append(paper.abstract)
                paper_texts.append(" ".join(text_parts) if text_parts else "No content")

            paper_embeddings = self.embedding_client.get_embeddings(paper_texts)

        except Exception as e:
            logger.error(f"Failed to generate embeddings for LLM themes: {e}")
            return []

        # Calculate maximum similarity to any theme for each paper
        results = []
        for idx, paper_emb in enumerate(paper_embeddings):
            # Find maximum similarity to any theme
            max_sim = 0.0
            best_theme_idx = 0

            for theme_idx, theme_emb in enumerate(theme_embeddings):
                sim = cosine_similarity(paper_emb, theme_emb)
                if sim > max_sim:
                    max_sim = sim
                    best_theme_idx = theme_idx

            if max_sim >= min_similarity:
                results.append(
                    RecommendationResult(
                        paper_id=papers[idx].id,
                        score=float(max_sim),
                        reason=f"Matches theme: '{themes[best_theme_idx]}' (similarity: {max_sim:.3f})",
                        strategy_name=self.strategy_name,
                    )
                )

        # Sort by score and return top-K
        results.sort(key=lambda r: r.score, reverse=True)
        logger.info(
            f"LLM themes: Generated {len(results)} recommendations "
            f"(min_similarity={min_similarity:.2f})"
        )

        return results[:top_k]

    def _generate_themes_from_papers(self, papers: List[Paper]) -> List[str]:
        """
        Generate interest themes from a list of papers using LLM.

        Args:
            papers: List of interested papers to analyze.

        Returns:
            List of theme strings (5-10 themes).

        Implementation:
            1. Prepares paper summaries for LLM
            2. Uses LLM to extract 5-10 key interest themes
            3. Returns themes as strings (no database storage)
        """
        # Limit to 30 most recent papers for context
        papers = papers[:30]

        # Prepare paper summaries for LLM
        paper_summaries = []
        for i, paper in enumerate(papers, 1):
            # Prioritize using TLDR or content_summary
            summary_text = None
            if paper.summaries:
                for summary in paper.summaries:
                    if summary.summary_type == "tldr":
                        summary_text = summary.content
                        break
                    elif summary.summary_type == "content_summary":
                        summary_text = summary.content

            # Fallback to abstract
            if not summary_text:
                if paper.abstract and len(paper.abstract.strip()) >= 50:
                    summary_text = paper.abstract[:500]
                else:
                    logger.warning(
                        f"Paper {paper.id} has no summary or valid abstract, skipping"
                    )
                    continue

            # Build summary entry
            summary = f"{i}. Title: {paper.title or 'N/A'}\n"
            if summary_text:
                summary += f"   Summary: {summary_text}\n"
            paper_summaries.append(summary)

        if not paper_summaries:
            logger.warning("No valid paper summaries for theme generation")
            return []

        papers_text = "\n\n".join(paper_summaries)

        # Generate themes using LLM
        system_prompt = """You are a research advisor analyzing a user's reading preferences.
Extract 5-10 key interest themes from the list of papers the user has marked as interested.

Each theme should:
- Be a concise phrase (2-6 words)
- Represent a specific research area or topic
- Be specific enough to distinguish from other themes

Return ONLY a JSON array of theme strings, no additional text.
Example format: ["Theme 1", "Theme 2", "Theme 3"]"""

        user_prompt = f"""Based on the following papers the user has recently marked as interested, extract the key research themes:

{papers_text}

Provide 5-10 themes that capture the user's main research interests."""

        try:
            response = self.llm_client.chat_with_system(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                temperature=0.7,
            )

            # Parse JSON response
            themes_json = response.strip()
            if themes_json.startswith("```"):
                themes_json = themes_json.split("```")[1]
                if themes_json.startswith("json"):
                    themes_json = themes_json[4:]

            themes = json.loads(themes_json)

            if not isinstance(themes, list):
                raise ValueError("LLM response is not a list")

            # Validate themes
            themes = [t for t in themes if isinstance(t, str) and len(t.strip()) > 0]

            if not themes:
                raise ValueError("No valid themes in LLM response")

            # Limit to 10 themes
            themes = themes[:10]

            logger.info(f"Generated {len(themes)} interest themes: {themes}")
            return themes

        except Exception as e:
            logger.error(f"Failed to generate themes with LLM: {e}")
            return []
